name: Save Stats to Output Branch

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Baixar stats
        id: download
        continue-on-error: true
        run: |
          mkdir -p dist
          curl -f -L "https://github-readme-stats.vercel.app/api?username=oandredev&hide_title=true&show_icons=true&include_all_commits=true&count_private=true&theme=algolia&hide_border=false" -o dist/github-stats.svg
          curl -f -L "https://github-readme-stats.vercel.app/api/top-langs?username=oandredev&layout=compact&langs_count=10&theme=algolia&hide_border=false" -o dist/top-langs.svg

      - name: Verificar se gerou corretamente
        id: check
        run: |
          if [ ! -s "dist/github-stats.svg" ] || [ ! -s "dist/top-langs.svg" ]; then
            echo "ok=false" >> $GITHUB_OUTPUT
          else
            echo "ok=true" >> $GITHUB_OUTPUT
          fi

      - name: Salvar no branch output (somente se OK)
        if: steps.check.outputs.ok == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout output 2>/dev/null || git checkout -b output

          cp dist/github-stats.svg .
          cp dist/top-langs.svg .

          git add github-stats.svg top-langs.svg
          git commit -m "Update stats (ok)" || echo "Nada para commitar"
          git push origin output
